# Generated by Django 2.1.5 on 2019-04-09 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_opioid', models.IntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DrugPrescriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_prescribed', models.IntegerField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescriber_id', models.BigIntegerField()),
                ('gender', models.TextField()),
                ('crendentials', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('specialty', models.TextField()),
                ('state', models.TextField()),
                ('is_opioid_prescriber', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='drugprescriber',
            name='prescriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Prescriber'),
        ),
    ]
